carve out generic install functions to own file

diff --git a/create-vm-image b/create-vm-image
--- a/create-vm-image
+++ b/create-vm-image
@@ -19,97 +19,6 @@ function usage() {
     echo "$0 Aborted."
 }
 
-#### Install our special files on machine ####################################
-function add_nafets_files {
-	local readonly name="$1"
-	local readonly mount="$2"
-
-	if [ $# -ne 2 ] ; then
-		printf "Internal Error: %s got %s parms (exp=2)\n" \
-			"$FUNCNAME" "$#" >&2
-		return 1
-	elif [ -z "$name" ] ; then
-		printf "Internal Error: Parm1 is null in %s \n" \
-			"$FUNCNAME" >&2
-		return 1
-	elif [ ! -d "$mount" ] ; then
-		printf "Internal Error: Directory %s does not exist in %s \n" \
-			"$mount" "$FUNCNAME" >&2
-		return 1
-	fi
-
-	# Exit on error
-	set -e
-
-	# Copy SSL private files
-	if [ -d /data/ca/$name ]; then
-		mkdir -p $mount/root/ssl.private
-		cp -L  /data/ca/$name/* $mount/root/ssl.private/
-		chown -R root:root $mount/root/ssl.private
-		chmod -R 400 $mount/root/ssl.private
-		printf "INSTALLED SSL Files\n" >&2
-	fi
-
-	#Get SubVersion Repository
-	svn checkout \
-		--username root@$name \
-		--password "" \
-		--non-interactive \
-		--quiet \
-		--config-dir $mount/root/.subversion \
-	        --config-option servers:global:store-plaintext-passwords=yes \
-	        svn://svn.intranet.nafets.de/tools/trunk \
-		$mount/root/tools
-	printf "INSTALLED subversion repository\n" >&2
-
-	# Copy local modified files to new machine
-	rsync -aHX --delete /root/tools/ $mount/root/tools --exclude=".svn"
-	printf "UPDATED subversion repository\n" >&2
-
-	return 0
-}
-
-#### Install a service that runs additional installations after first boot ###
-function setup_install_service () {
-	# Parameter:
-	#    1 - mounted_rootdir
-	#    2 - Install type - matches to /root/install/install-<type>.sh
-	#        that will be called on first boot
-	if [ ! -d $1/etc/systemd/system ] ; then
-		printf "Internal Error: %s is not a directory.\n" \
-			"$1/etc/systemd/system" >&2
-		return 1
-	elif [ ! -e $1/root/tools/install/install-$2.sh ] ; then
-		printf "Warning: Skipping Install-service (no %s).\n" \
-			"$1/root/tools/install/install-$2.sh" >&2
-		return 0
-	fi
-	printf "Installing Install-Service for machine type %s.\n" "$2" >&2
-	cat >>$1/etc/systemd/system/nafetsde-install.service <<-EOF
-		# nafetsde-install.service
-		#
-		# (C) 2017 Stefan Schallenberg
-		#
-		[Unit]
-		Description="Install $2 machine after first boot (nafets.de)"
-		ConditionPathExists=!/var/lib/nafetsde-install/.done
-
-		[Service]
-		Type=oneshot
-		ExecStart=/root/tools/install/install-$2.sh
-		ExecStartPost=/root/tools/install/install.sh install_env_expire_std_root_pw
-		ExecStartPost=/bin/mkdir -p /var/lib/nafetsde-install
-		ExecStartPost=/bin/touch /var/lib/nafetsde-install/.done
-
-		[Install]
-		WantedBy=multi-user.target
-		EOF
-		
-	arch-chroot $1 <<-EOF
-		systemctl enable nafetsde-install.service
-	EOF
-
-}
 #### Install Arch Linux on a mounted directory ###############################
 function install_arch_ondir () {
 # Parameters: 
@@ -187,7 +96,7 @@ arch-chroot $2 <<EOF
     (echo "password1"; echo "password1") | passwd
 EOF
 
-add_nafets_files "$1" "$2"
+install_nafets_files "$1" "$2"
 
 for f in $machboot ; do case "$f" in
 	grubcfg) 
@@ -254,7 +163,7 @@ if [ -z "$6" ] ; then
 	EOF
 	echo "Remember to setup up networking in the new machine, its not done yet!" 
 else
-	setup_install_service "$2" "${6,,}"
+	install_setup_service "$2" "${6,,}"
 	rc=$? ; if [ $rc -ne 0 ] ; then return $rc; fi
 fi
 
@@ -815,7 +724,7 @@ function do_install_coreos-ct {
 	mount $ROOTDEV $MNTDIR || \
 		{ echo "Could not mount $ROOTDEV on $MNTDIR" >&2; exit 1 ; }
 		
-	add_nafets_files "$1" "$MNTDIR"
+	install_nafets_files "$1" "$MNTDIR"
 
 	umount $MNTDIR
 	kpartx -d /dev/mapper/$MNTNAME
@@ -941,6 +850,13 @@ function do_install_usb () {
 
 
 ##### main ####################################################################
+. $(dirname $BASH_SOURCE)/install-functions.sh
+if [ $? -ne 0 ] ; then 
+	printf "install-functions.sh not found. Aborting.\n"
+	exit 1
+fi
+
+
 if [ $# -lt 1 ]; then
 	usage "Got $# arguments, minimum 1 expected"
 else
